/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnomalyDnaRouteImport } from './routes/anomaly-dna'
import { Route as DataOperationsRouteImport } from './routes/data-operations'
import { Route as EdgeSimulatorRouteImport } from './routes/edge-simulator'
import { Route as FairValueRouteImport } from './routes/fair-value'
import { Route as RiskRadarRouteImport } from './routes/risk-radar'
import { Route as StrategyLabRouteImport } from './routes/strategy-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomalyDnaRoute = AnomalyDnaRouteImport.update({
  id: '/anomaly-dna',
  path: '/anomaly-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const DataOperationsRoute = DataOperationsRouteImport.update({
  id: '/data-operations',
  path: '/data-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const EdgeSimulatorRoute = EdgeSimulatorRouteImport.update({
  id: '/edge-simulator',
  path: '/edge-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const FairValueRoute = FairValueRouteImport.update({
  id: '/fair-value',
  path: '/fair-value',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRadarRoute = RiskRadarRouteImport.update({
  id: '/risk-radar',
  path: '/risk-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyLabRoute = StrategyLabRouteImport.update({
  id: '/strategy-lab',
  path: '/strategy-lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anomaly-dna': typeof AnomalyDnaRoute
  '/data-operations': typeof DataOperationsRoute
  '/edge-simulator': typeof EdgeSimulatorRoute
  '/fair-value': typeof FairValueRoute
  '/risk-radar': typeof RiskRadarRoute
  '/strategy-lab': typeof StrategyLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anomaly-dna': typeof AnomalyDnaRoute
  '/data-operations': typeof DataOperationsRoute
  '/edge-simulator': typeof EdgeSimulatorRoute
  '/fair-value': typeof FairValueRoute
  '/risk-radar': typeof RiskRadarRoute
  '/strategy-lab': typeof StrategyLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anomaly-dna': typeof AnomalyDnaRoute
  '/data-operations': typeof DataOperationsRoute
  '/edge-simulator': typeof EdgeSimulatorRoute
  '/fair-value': typeof FairValueRoute
  '/risk-radar': typeof RiskRadarRoute
  '/strategy-lab': typeof StrategyLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anomaly-dna'
    | '/data-operations'
    | '/edge-simulator'
    | '/fair-value'
    | '/risk-radar'
    | '/strategy-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anomaly-dna'
    | '/data-operations'
    | '/edge-simulator'
    | '/fair-value'
    | '/risk-radar'
    | '/strategy-lab'
  id:
    | '__root__'
    | '/'
    | '/anomaly-dna'
    | '/data-operations'
    | '/edge-simulator'
    | '/fair-value'
    | '/risk-radar'
    | '/strategy-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnomalyDnaRoute: typeof AnomalyDnaRoute
  DataOperationsRoute: typeof DataOperationsRoute
  EdgeSimulatorRoute: typeof EdgeSimulatorRoute
  FairValueRoute: typeof FairValueRoute
  RiskRadarRoute: typeof RiskRadarRoute
  StrategyLabRoute: typeof StrategyLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomaly-dna': {
      id: '/anomaly-dna'
      path: '/anomaly-dna'
      fullPath: '/anomaly-dna'
      preLoaderRoute: typeof AnomalyDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-operations': {
      id: '/data-operations'
      path: '/data-operations'
      fullPath: '/data-operations'
      preLoaderRoute: typeof DataOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edge-simulator': {
      id: '/edge-simulator'
      path: '/edge-simulator'
      fullPath: '/edge-simulator'
      preLoaderRoute: typeof EdgeSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fair-value': {
      id: '/fair-value'
      path: '/fair-value'
      fullPath: '/fair-value'
      preLoaderRoute: typeof FairValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-radar': {
      id: '/risk-radar'
      path: '/risk-radar'
      fullPath: '/risk-radar'
      preLoaderRoute: typeof RiskRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy-lab': {
      id: '/strategy-lab'
      path: '/strategy-lab'
      fullPath: '/strategy-lab'
      preLoaderRoute: typeof StrategyLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnomalyDnaRoute: AnomalyDnaRoute,
  DataOperationsRoute: DataOperationsRoute,
  EdgeSimulatorRoute: EdgeSimulatorRoute,
  FairValueRoute: FairValueRoute,
  RiskRadarRoute: RiskRadarRoute,
  StrategyLabRoute: StrategyLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
